tests: pass download_process_info to avoid comparison error
Avoids the following issue:

```
self = <[AttributeError("'Process' object has no attribute '_pid'") raised in repr()] Process object at 0x1c6d49cbce0>, pid = <Mock name='mock.download_process_info.os_pid' id='1953480516112'>, _ignore_nsp = False

    def _init(self, pid, _ignore_nsp=False):
        if pid is None:
            pid = os.getpid()
        else:
>           if pid < 0:
               ^^^^^^^